// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package timeseriesconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import timeseriesconnector.helpers.Aggregation;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_AggregateBetweenTimestamps extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject aggregationParameter;
	private String assetID;
	private String channelKey;
	private Long startDate;
	private Long endDate;
	private timeseriesconnector.proxies.Enum_AggregationPeriod aggregationPeriod;
	private String timeZone;
	private String measurementType;

	public JA_AggregateBetweenTimestamps(IContext context, IMendixObject aggregationParameter, String assetID, String channelKey, Long startDate, Long endDate, String aggregationPeriod, String timeZone, String measurementType)
	{
		super(context);
		this.aggregationParameter = aggregationParameter;
		this.assetID = assetID;
		this.channelKey = channelKey;
		this.startDate = startDate;
		this.endDate = endDate;
		this.aggregationPeriod = aggregationPeriod == null ? null : timeseriesconnector.proxies.Enum_AggregationPeriod.valueOf(aggregationPeriod);
		this.timeZone = timeZone;
		this.measurementType = measurementType;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Aggregation.aggregateBetweenTimestamps(aggregationParameter, assetID, channelKey, startDate, endDate, aggregationPeriod.toString(), timeZone, measurementType, this.getContext());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JA_AggregateBetweenTimestamps";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
