// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package timeseriesconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import timeseriesconnector.helpers.*;

/**
 * Create an asset.
 */
public class JA_CreateAsset extends CustomJavaAction<String>
{
	private String assetName;

	public JA_CreateAsset(IContext context, String assetName)
	{
		super(context);
		this.assetName = assetName;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
			return AssetManagement.createAsset(assetName, this.getContext());
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JA_CreateAsset";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
