// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package timeseriesconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import timeseriesconnector.helpers.AssetManagement;

public class JA_DeleteAsset extends CustomJavaAction<Boolean>
{
	private String assetId;

	public JA_DeleteAsset(IContext context, String assetId)
	{
		super(context);
		this.assetId = assetId;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return AssetManagement.deleteAsset(assetId);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JA_DeleteAsset";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
