// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package timeseriesconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import timeseriesconnector.helpers.AssetManagement;

/**
 * Deletes a channel from a specific asset
 * 
 * parameters:
 * 
 * assetID : the ID of the asset from which to delete the channel
 * channelKey: the key of the channel to delete
 */
public class JA_DeleteChannel extends CustomJavaAction<Boolean>
{
	private String assetID;
	private String channelKey;

	public JA_DeleteChannel(IContext context, String assetID, String channelKey)
	{
		super(context);
		this.assetID = assetID;
		this.channelKey = channelKey;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return AssetManagement.deleteChannel(this.getContext(), assetID, channelKey);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JA_DeleteChannel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
