// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timeseriesconnector.proxies;

public class AssetSearchResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assetSearchResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TimeSeriesConnector.AssetSearchResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		assetID("assetID"),
		name("name"),
		AssetNP_Search("TimeSeriesConnector.AssetNP_Search");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AssetSearchResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TimeSeriesConnector.AssetSearchResult"));
	}

	protected AssetSearchResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assetSearchResultMendixObject)
	{
		if (assetSearchResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TimeSeriesConnector.AssetSearchResult", assetSearchResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TimeSeriesConnector.AssetSearchResult");

		this.assetSearchResultMendixObject = assetSearchResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AssetSearchResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static timeseriesconnector.proxies.AssetSearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return timeseriesconnector.proxies.AssetSearchResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static timeseriesconnector.proxies.AssetSearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new timeseriesconnector.proxies.AssetSearchResult(context, mendixObject);
	}

	public static timeseriesconnector.proxies.AssetSearchResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return timeseriesconnector.proxies.AssetSearchResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of assetID
	 */
	public final String getassetID()
	{
		return getassetID(getContext());
	}

	/**
	 * @param context
	 * @return value of assetID
	 */
	public final String getassetID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.assetID.toString());
	}

	/**
	 * Set value of assetID
	 * @param assetid
	 */
	public final void setassetID(String assetid)
	{
		setassetID(getContext(), assetid);
	}

	/**
	 * Set value of assetID
	 * @param context
	 * @param assetid
	 */
	public final void setassetID(com.mendix.systemwideinterfaces.core.IContext context, String assetid)
	{
		getMendixObject().setValue(context, MemberNames.assetID.toString(), assetid);
	}

	/**
	 * @return value of name
	 */
	public final String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of AssetNP_Search
	 */
	public final timeseriesconnector.proxies.Search getAssetNP_Search() throws com.mendix.core.CoreException
	{
		return getAssetNP_Search(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetNP_Search
	 */
	public final timeseriesconnector.proxies.Search getAssetNP_Search(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timeseriesconnector.proxies.Search result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AssetNP_Search.toString());
		if (identifier != null)
			result = timeseriesconnector.proxies.Search.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AssetNP_Search
	 * @param assetnp_search
	 */
	public final void setAssetNP_Search(timeseriesconnector.proxies.Search assetnp_search)
	{
		setAssetNP_Search(getContext(), assetnp_search);
	}

	/**
	 * Set value of AssetNP_Search
	 * @param context
	 * @param assetnp_search
	 */
	public final void setAssetNP_Search(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.Search assetnp_search)
	{
		if (assetnp_search == null)
			getMendixObject().setValue(context, MemberNames.AssetNP_Search.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AssetNP_Search.toString(), assetnp_search.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assetSearchResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final timeseriesconnector.proxies.AssetSearchResult that = (timeseriesconnector.proxies.AssetSearchResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TimeSeriesConnector.AssetSearchResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
