// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timeseriesconnector.proxies;

public class MeasurementSearch
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject measurementSearchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TimeSeriesConnector.MeasurementSearch";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		measurementType("measurementType"),
		dateTimeStart("dateTimeStart"),
		dateTimeEnd("dateTimeEnd"),
		dateTimeStartEpoch("dateTimeStartEpoch"),
		dateTimeEndEpoch("dateTimeEndEpoch"),
		limit("limit"),
		searchType("searchType"),
		MeasurementSearch_Asset("TimeSeriesConnector.MeasurementSearch_Asset"),
		MeasurementSearch_Channel("TimeSeriesConnector.MeasurementSearch_Channel");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MeasurementSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TimeSeriesConnector.MeasurementSearch"));
	}

	protected MeasurementSearch(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject measurementSearchMendixObject)
	{
		if (measurementSearchMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TimeSeriesConnector.MeasurementSearch", measurementSearchMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TimeSeriesConnector.MeasurementSearch");

		this.measurementSearchMendixObject = measurementSearchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MeasurementSearch.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static timeseriesconnector.proxies.MeasurementSearch initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return timeseriesconnector.proxies.MeasurementSearch.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static timeseriesconnector.proxies.MeasurementSearch initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new timeseriesconnector.proxies.MeasurementSearch(context, mendixObject);
	}

	public static timeseriesconnector.proxies.MeasurementSearch load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return timeseriesconnector.proxies.MeasurementSearch.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of measurementType
	 */
	public final String getmeasurementType()
	{
		return getmeasurementType(getContext());
	}

	/**
	 * @param context
	 * @return value of measurementType
	 */
	public final String getmeasurementType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.measurementType.toString());
	}

	/**
	 * Set value of measurementType
	 * @param measurementtype
	 */
	public final void setmeasurementType(String measurementtype)
	{
		setmeasurementType(getContext(), measurementtype);
	}

	/**
	 * Set value of measurementType
	 * @param context
	 * @param measurementtype
	 */
	public final void setmeasurementType(com.mendix.systemwideinterfaces.core.IContext context, String measurementtype)
	{
		getMendixObject().setValue(context, MemberNames.measurementType.toString(), measurementtype);
	}

	/**
	 * @return value of dateTimeStart
	 */
	public final java.util.Date getdateTimeStart()
	{
		return getdateTimeStart(getContext());
	}

	/**
	 * @param context
	 * @return value of dateTimeStart
	 */
	public final java.util.Date getdateTimeStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dateTimeStart.toString());
	}

	/**
	 * Set value of dateTimeStart
	 * @param datetimestart
	 */
	public final void setdateTimeStart(java.util.Date datetimestart)
	{
		setdateTimeStart(getContext(), datetimestart);
	}

	/**
	 * Set value of dateTimeStart
	 * @param context
	 * @param datetimestart
	 */
	public final void setdateTimeStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimestart)
	{
		getMendixObject().setValue(context, MemberNames.dateTimeStart.toString(), datetimestart);
	}

	/**
	 * @return value of dateTimeEnd
	 */
	public final java.util.Date getdateTimeEnd()
	{
		return getdateTimeEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of dateTimeEnd
	 */
	public final java.util.Date getdateTimeEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dateTimeEnd.toString());
	}

	/**
	 * Set value of dateTimeEnd
	 * @param datetimeend
	 */
	public final void setdateTimeEnd(java.util.Date datetimeend)
	{
		setdateTimeEnd(getContext(), datetimeend);
	}

	/**
	 * Set value of dateTimeEnd
	 * @param context
	 * @param datetimeend
	 */
	public final void setdateTimeEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimeend)
	{
		getMendixObject().setValue(context, MemberNames.dateTimeEnd.toString(), datetimeend);
	}

	/**
	 * @return value of dateTimeStartEpoch
	 */
	public final Long getdateTimeStartEpoch()
	{
		return getdateTimeStartEpoch(getContext());
	}

	/**
	 * @param context
	 * @return value of dateTimeStartEpoch
	 */
	public final Long getdateTimeStartEpoch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.dateTimeStartEpoch.toString());
	}

	/**
	 * Set value of dateTimeStartEpoch
	 * @param datetimestartepoch
	 */
	public final void setdateTimeStartEpoch(Long datetimestartepoch)
	{
		setdateTimeStartEpoch(getContext(), datetimestartepoch);
	}

	/**
	 * Set value of dateTimeStartEpoch
	 * @param context
	 * @param datetimestartepoch
	 */
	public final void setdateTimeStartEpoch(com.mendix.systemwideinterfaces.core.IContext context, Long datetimestartepoch)
	{
		getMendixObject().setValue(context, MemberNames.dateTimeStartEpoch.toString(), datetimestartepoch);
	}

	/**
	 * @return value of dateTimeEndEpoch
	 */
	public final Long getdateTimeEndEpoch()
	{
		return getdateTimeEndEpoch(getContext());
	}

	/**
	 * @param context
	 * @return value of dateTimeEndEpoch
	 */
	public final Long getdateTimeEndEpoch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.dateTimeEndEpoch.toString());
	}

	/**
	 * Set value of dateTimeEndEpoch
	 * @param datetimeendepoch
	 */
	public final void setdateTimeEndEpoch(Long datetimeendepoch)
	{
		setdateTimeEndEpoch(getContext(), datetimeendepoch);
	}

	/**
	 * Set value of dateTimeEndEpoch
	 * @param context
	 * @param datetimeendepoch
	 */
	public final void setdateTimeEndEpoch(com.mendix.systemwideinterfaces.core.IContext context, Long datetimeendepoch)
	{
		getMendixObject().setValue(context, MemberNames.dateTimeEndEpoch.toString(), datetimeendepoch);
	}

	/**
	 * @return value of limit
	 */
	public final Integer getlimit()
	{
		return getlimit(getContext());
	}

	/**
	 * @param context
	 * @return value of limit
	 */
	public final Integer getlimit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.limit.toString());
	}

	/**
	 * Set value of limit
	 * @param limit
	 */
	public final void setlimit(Integer limit)
	{
		setlimit(getContext(), limit);
	}

	/**
	 * Set value of limit
	 * @param context
	 * @param limit
	 */
	public final void setlimit(com.mendix.systemwideinterfaces.core.IContext context, Integer limit)
	{
		getMendixObject().setValue(context, MemberNames.limit.toString(), limit);
	}

	/**
	 * Set value of searchType
	 * @param searchtype
	 */
	public final timeseriesconnector.proxies.Enum_SearchType getsearchType()
	{
		return getsearchType(getContext());
	}

	/**
	 * @param context
	 * @return value of searchType
	 */
	public final timeseriesconnector.proxies.Enum_SearchType getsearchType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.searchType.toString());
		if (obj == null)
			return null;

		return timeseriesconnector.proxies.Enum_SearchType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of searchType
	 * @param searchtype
	 */
	public final void setsearchType(timeseriesconnector.proxies.Enum_SearchType searchtype)
	{
		setsearchType(getContext(), searchtype);
	}

	/**
	 * Set value of searchType
	 * @param context
	 * @param searchtype
	 */
	public final void setsearchType(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.Enum_SearchType searchtype)
	{
		if (searchtype != null)
			getMendixObject().setValue(context, MemberNames.searchType.toString(), searchtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.searchType.toString(), null);
	}

	/**
	 * @return value of MeasurementSearch_Asset
	 */
	public final timeseriesconnector.proxies.Asset getMeasurementSearch_Asset() throws com.mendix.core.CoreException
	{
		return getMeasurementSearch_Asset(getContext());
	}

	/**
	 * @param context
	 * @return value of MeasurementSearch_Asset
	 */
	public final timeseriesconnector.proxies.Asset getMeasurementSearch_Asset(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timeseriesconnector.proxies.Asset result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MeasurementSearch_Asset.toString());
		if (identifier != null)
			result = timeseriesconnector.proxies.Asset.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MeasurementSearch_Asset
	 * @param measurementsearch_asset
	 */
	public final void setMeasurementSearch_Asset(timeseriesconnector.proxies.Asset measurementsearch_asset)
	{
		setMeasurementSearch_Asset(getContext(), measurementsearch_asset);
	}

	/**
	 * Set value of MeasurementSearch_Asset
	 * @param context
	 * @param measurementsearch_asset
	 */
	public final void setMeasurementSearch_Asset(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.Asset measurementsearch_asset)
	{
		if (measurementsearch_asset == null)
			getMendixObject().setValue(context, MemberNames.MeasurementSearch_Asset.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MeasurementSearch_Asset.toString(), measurementsearch_asset.getMendixObject().getId());
	}

	/**
	 * @return value of MeasurementSearch_Channel
	 */
	public final timeseriesconnector.proxies.Channel getMeasurementSearch_Channel() throws com.mendix.core.CoreException
	{
		return getMeasurementSearch_Channel(getContext());
	}

	/**
	 * @param context
	 * @return value of MeasurementSearch_Channel
	 */
	public final timeseriesconnector.proxies.Channel getMeasurementSearch_Channel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timeseriesconnector.proxies.Channel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MeasurementSearch_Channel.toString());
		if (identifier != null)
			result = timeseriesconnector.proxies.Channel.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MeasurementSearch_Channel
	 * @param measurementsearch_channel
	 */
	public final void setMeasurementSearch_Channel(timeseriesconnector.proxies.Channel measurementsearch_channel)
	{
		setMeasurementSearch_Channel(getContext(), measurementsearch_channel);
	}

	/**
	 * Set value of MeasurementSearch_Channel
	 * @param context
	 * @param measurementsearch_channel
	 */
	public final void setMeasurementSearch_Channel(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.Channel measurementsearch_channel)
	{
		if (measurementsearch_channel == null)
			getMendixObject().setValue(context, MemberNames.MeasurementSearch_Channel.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MeasurementSearch_Channel.toString(), measurementsearch_channel.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return measurementSearchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final timeseriesconnector.proxies.MeasurementSearch that = (timeseriesconnector.proxies.MeasurementSearch) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TimeSeriesConnector.MeasurementSearch";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
