// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timeseriesconnector.proxies;

public class RawMeasurementNP
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rawMeasurementNPMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TimeSeriesConnector.RawMeasurementNP";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		assetID("assetID"),
		channelKey("channelKey"),
		dateTime("dateTime"),
		measurementType("measurementType"),
		value("value"),
		RawMeasurementNP_MeasurementSearch("TimeSeriesConnector.RawMeasurementNP_MeasurementSearch");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RawMeasurementNP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TimeSeriesConnector.RawMeasurementNP"));
	}

	protected RawMeasurementNP(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rawMeasurementNPMendixObject)
	{
		if (rawMeasurementNPMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TimeSeriesConnector.RawMeasurementNP", rawMeasurementNPMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TimeSeriesConnector.RawMeasurementNP");

		this.rawMeasurementNPMendixObject = rawMeasurementNPMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RawMeasurementNP.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static timeseriesconnector.proxies.RawMeasurementNP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return timeseriesconnector.proxies.RawMeasurementNP.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static timeseriesconnector.proxies.RawMeasurementNP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new timeseriesconnector.proxies.RawMeasurementNP(context, mendixObject);
	}

	public static timeseriesconnector.proxies.RawMeasurementNP load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return timeseriesconnector.proxies.RawMeasurementNP.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of assetID
	 */
	public final String getassetID()
	{
		return getassetID(getContext());
	}

	/**
	 * @param context
	 * @return value of assetID
	 */
	public final String getassetID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.assetID.toString());
	}

	/**
	 * Set value of assetID
	 * @param assetid
	 */
	public final void setassetID(String assetid)
	{
		setassetID(getContext(), assetid);
	}

	/**
	 * Set value of assetID
	 * @param context
	 * @param assetid
	 */
	public final void setassetID(com.mendix.systemwideinterfaces.core.IContext context, String assetid)
	{
		getMendixObject().setValue(context, MemberNames.assetID.toString(), assetid);
	}

	/**
	 * @return value of channelKey
	 */
	public final String getchannelKey()
	{
		return getchannelKey(getContext());
	}

	/**
	 * @param context
	 * @return value of channelKey
	 */
	public final String getchannelKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.channelKey.toString());
	}

	/**
	 * Set value of channelKey
	 * @param channelkey
	 */
	public final void setchannelKey(String channelkey)
	{
		setchannelKey(getContext(), channelkey);
	}

	/**
	 * Set value of channelKey
	 * @param context
	 * @param channelkey
	 */
	public final void setchannelKey(com.mendix.systemwideinterfaces.core.IContext context, String channelkey)
	{
		getMendixObject().setValue(context, MemberNames.channelKey.toString(), channelkey);
	}

	/**
	 * @return value of dateTime
	 */
	public final String getdateTime()
	{
		return getdateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of dateTime
	 */
	public final String getdateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.dateTime.toString());
	}

	/**
	 * Set value of dateTime
	 * @param datetime
	 */
	public final void setdateTime(String datetime)
	{
		setdateTime(getContext(), datetime);
	}

	/**
	 * Set value of dateTime
	 * @param context
	 * @param datetime
	 */
	public final void setdateTime(com.mendix.systemwideinterfaces.core.IContext context, String datetime)
	{
		getMendixObject().setValue(context, MemberNames.dateTime.toString(), datetime);
	}

	/**
	 * @return value of measurementType
	 */
	public final String getmeasurementType()
	{
		return getmeasurementType(getContext());
	}

	/**
	 * @param context
	 * @return value of measurementType
	 */
	public final String getmeasurementType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.measurementType.toString());
	}

	/**
	 * Set value of measurementType
	 * @param measurementtype
	 */
	public final void setmeasurementType(String measurementtype)
	{
		setmeasurementType(getContext(), measurementtype);
	}

	/**
	 * Set value of measurementType
	 * @param context
	 * @param measurementtype
	 */
	public final void setmeasurementType(com.mendix.systemwideinterfaces.core.IContext context, String measurementtype)
	{
		getMendixObject().setValue(context, MemberNames.measurementType.toString(), measurementtype);
	}

	/**
	 * @return value of value
	 */
	public final java.math.BigDecimal getvalue()
	{
		return getvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of value
	 */
	public final java.math.BigDecimal getvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.value.toString());
	}

	/**
	 * Set value of value
	 * @param value
	 */
	public final void setvalue(java.math.BigDecimal value)
	{
		setvalue(getContext(), value);
	}

	/**
	 * Set value of value
	 * @param context
	 * @param value
	 */
	public final void setvalue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal value)
	{
		getMendixObject().setValue(context, MemberNames.value.toString(), value);
	}

	/**
	 * @return value of RawMeasurementNP_MeasurementSearch
	 */
	public final timeseriesconnector.proxies.MeasurementSearch getRawMeasurementNP_MeasurementSearch() throws com.mendix.core.CoreException
	{
		return getRawMeasurementNP_MeasurementSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of RawMeasurementNP_MeasurementSearch
	 */
	public final timeseriesconnector.proxies.MeasurementSearch getRawMeasurementNP_MeasurementSearch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		timeseriesconnector.proxies.MeasurementSearch result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RawMeasurementNP_MeasurementSearch.toString());
		if (identifier != null)
			result = timeseriesconnector.proxies.MeasurementSearch.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RawMeasurementNP_MeasurementSearch
	 * @param rawmeasurementnp_measurementsearch
	 */
	public final void setRawMeasurementNP_MeasurementSearch(timeseriesconnector.proxies.MeasurementSearch rawmeasurementnp_measurementsearch)
	{
		setRawMeasurementNP_MeasurementSearch(getContext(), rawmeasurementnp_measurementsearch);
	}

	/**
	 * Set value of RawMeasurementNP_MeasurementSearch
	 * @param context
	 * @param rawmeasurementnp_measurementsearch
	 */
	public final void setRawMeasurementNP_MeasurementSearch(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.MeasurementSearch rawmeasurementnp_measurementsearch)
	{
		if (rawmeasurementnp_measurementsearch == null)
			getMendixObject().setValue(context, MemberNames.RawMeasurementNP_MeasurementSearch.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RawMeasurementNP_MeasurementSearch.toString(), rawmeasurementnp_measurementsearch.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rawMeasurementNPMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final timeseriesconnector.proxies.RawMeasurementNP that = (timeseriesconnector.proxies.RawMeasurementNP) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TimeSeriesConnector.RawMeasurementNP";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
