// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package timeseriesconnector.proxies;

public class Search
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TimeSeriesConnector.Search";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nameToSearch("nameToSearch"),
		idToSearch("idToSearch"),
		searchBy("searchBy");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Search(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TimeSeriesConnector.Search"));
	}

	protected Search(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject)
	{
		if (searchMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TimeSeriesConnector.Search", searchMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TimeSeriesConnector.Search");

		this.searchMendixObject = searchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Search.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static timeseriesconnector.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return timeseriesconnector.proxies.Search.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static timeseriesconnector.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new timeseriesconnector.proxies.Search(context, mendixObject);
	}

	public static timeseriesconnector.proxies.Search load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return timeseriesconnector.proxies.Search.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of nameToSearch
	 */
	public final String getnameToSearch()
	{
		return getnameToSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of nameToSearch
	 */
	public final String getnameToSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.nameToSearch.toString());
	}

	/**
	 * Set value of nameToSearch
	 * @param nametosearch
	 */
	public final void setnameToSearch(String nametosearch)
	{
		setnameToSearch(getContext(), nametosearch);
	}

	/**
	 * Set value of nameToSearch
	 * @param context
	 * @param nametosearch
	 */
	public final void setnameToSearch(com.mendix.systemwideinterfaces.core.IContext context, String nametosearch)
	{
		getMendixObject().setValue(context, MemberNames.nameToSearch.toString(), nametosearch);
	}

	/**
	 * @return value of idToSearch
	 */
	public final String getidToSearch()
	{
		return getidToSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of idToSearch
	 */
	public final String getidToSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.idToSearch.toString());
	}

	/**
	 * Set value of idToSearch
	 * @param idtosearch
	 */
	public final void setidToSearch(String idtosearch)
	{
		setidToSearch(getContext(), idtosearch);
	}

	/**
	 * Set value of idToSearch
	 * @param context
	 * @param idtosearch
	 */
	public final void setidToSearch(com.mendix.systemwideinterfaces.core.IContext context, String idtosearch)
	{
		getMendixObject().setValue(context, MemberNames.idToSearch.toString(), idtosearch);
	}

	/**
	 * Set value of searchBy
	 * @param searchby
	 */
	public final timeseriesconnector.proxies.SearchByType getsearchBy()
	{
		return getsearchBy(getContext());
	}

	/**
	 * @param context
	 * @return value of searchBy
	 */
	public final timeseriesconnector.proxies.SearchByType getsearchBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.searchBy.toString());
		if (obj == null)
			return null;

		return timeseriesconnector.proxies.SearchByType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of searchBy
	 * @param searchby
	 */
	public final void setsearchBy(timeseriesconnector.proxies.SearchByType searchby)
	{
		setsearchBy(getContext(), searchby);
	}

	/**
	 * Set value of searchBy
	 * @param context
	 * @param searchby
	 */
	public final void setsearchBy(com.mendix.systemwideinterfaces.core.IContext context, timeseriesconnector.proxies.SearchByType searchby)
	{
		if (searchby != null)
			getMendixObject().setValue(context, MemberNames.searchBy.toString(), searchby.toString());
		else
			getMendixObject().setValue(context, MemberNames.searchBy.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final timeseriesconnector.proxies.Search that = (timeseriesconnector.proxies.Search) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TimeSeriesConnector.Search";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
